spring:
  datasource:
      url: jdbc:mysql://localhost:3306/Same_Day_Flight_Change?useSSL=false
      username: dbchanges
      password: Wq1kop6LnrnkTZX
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    open-in-view: false